### ISSUE TITLE
Question on the removed `HEALTHCHECK`

### ISSUE THREAD

**Issue by larssb** [klutchell/dnscrypt-proxy#19]
Hi @klutchell,

As it can be seen in commit [remove drill and internal healthcheck](https://github.com/klutchell/dnscrypt-proxy/commit/ec2e400fc2fa4dff5ec0736dd52c278a28660922) the `HEALTHCHECK` was removed. My question is, why was it removed?
The reason I ask is because I'm trying to use [this `dnscrypt-proxy`](https://github.com/djaydev/docker-dnscrypt-proxy) container image and it uses the same `HEALTHCHECK`.
But, if the `drill` cmd is taking a long time to complete the time out kicks in and that seems to leave `drill` processes in a *zombie* state. Causing a resource limit issue. As *zombie* processes still counts against the max user open processes. And that number is at some point met.
So some background on why it was removed would be lovely.

Thank you very much and a Happy Easter

**Comment by klutchell** [comment]
Hmm, my commit message isn't very helpful is it.

If my memory serves, it was just a matter of keeping the image as simple as possible, and as part of that I would prefer it be up to the user to set a healthcheck at runtime if they want one, as long as the required components are present to do so.

In fact, I probably considered adding an example to run with a healthcheck in the README but forgot to add it. Since there are some cases where a healthcheck may be undesirable or not work at all, I'd rather it be opt-in only :)

**Comment by larssb** [comment]
Hi @klutchell,

Thank you for replying so quickly. I'm totally okay with your though on letting the user just providing a `HEALTHCHECK` at runtime.

Thank you and stay home and safe 👍
